name: Bug Report
description: Report a bug or issue with the E-Voting System
title: '[BUG] '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system is affected?
      options:
        - Frontend (React)
        - Backend (Flask)
        - Authentication
        - Voting System
        - Admin Dashboard
        - Database
        - Other
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your system information
      value: |
        - OS: [e.g. macOS, Windows 11]
        - Browser: [e.g. Chrome, Safari]
        - Python Version: [e.g. 3.9]
        - Node.js Version: [e.g. 18.0]
    validations:
      required: true
