name: Feature Request
description: Suggest a new feature or enhancement
title: '[FEATURE] '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What would you like to see added?
      placeholder: Describe the feature you'd like to see
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem this feature would solve
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system would this affect?
      options:
        - Frontend (React)
        - Backend (Flask)
        - Authentication
        - Voting System
        - Admin Dashboard
        - Database
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Additional Context
      description: Please check all that apply
      options:
        - label: This feature would improve security
        - label: This feature would improve user experience
        - label: This feature would improve performance
        - label: This feature would improve accessibility
        - label: I'm willing to help implement this feature
